---
name: haproxy

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: haproxy
  azs: [az1]
  instances: 2
  vm_type: medium
  stemcell: default
  networks: [{name: runtime}]
  jobs:
  - name: haproxy
    release: haproxy
    properties:
      ha_proxy:
        backend_port: ((haproxy-backend-port))
        backend_servers: ((haproxy-backend-servers))
        stats_enable: true
        stats_promex_enable: true
        trusted_stats_cidrs: 10.250.10.0/24
        ssl_pem:
        - cert_chain: ((apps-cert-chain))
          private_key: ((apps-priv-key))
        - cert_chain: ((sys-cert-chain))
          private_key: ((sys-priv-key))
        tcp:
        - name: ssh-proxy
          port: 2222
          backend_servers:
          - ssh-proxy.service.cf.internal

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-jammy
    version: latest

releases:
- name: bpm
  version: 1.2.14
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.2.14
  sha1: 1e357a533654e2067e15231dd8ac5bad2e697dff
- name: haproxy
  version: 14.3.0+2.8.10
  url: https://github.com/cloudfoundry/haproxy-boshrelease/releases/download/v14.3.0+2.8.10/haproxy-14.3.0+2.8.10.tgz
  sha1: dae9acded29dd91ae0796441fae298143d56a724
